### PR TITLE
Fixed inline editing by removing assets from the form type

### LINKED ISSUE #327: A better way of importing JS resources for tree input
Currently, the JS and CSS files required for the JS input are loaded at the field itself. This doesn't result in a very great page rendering:
1. The page renders until the tree field
2. It then waits to load all the files and execute the javascript
3. After that happend, the rest of the page is rendered

It also means that including the tree field 3 times would lead to loading all assets 3 times.

### PR DESCRIPTION
**Pull request by wouterj**
Closes #327

## Changelog

```markdown
### Added
- Added `AddTreeBrowserAssetsPass` to load TreeBrowser assets using the admin pool
- Added a custom form theme for the TreeSelectType in order to use AdminLTE
```

## Subject

When adding support for inline editing, an AJAX request is done to load the form. Since the TreeSelectType includes `<script>` tags, calling `.replaceWith(html)` will result in a blank page. Also, as you can read in #327, loading fancytree for each usage of the form type isn't needed. Loading it only once in the head would be much better.

This PR fixes both issues by configuring the admin pool to include the fancytree assets. It also overrides the TreeSelectType to avoid loading these assets again.

Meanwhile, I also added some AdminLTE styles to the TreeSelectType to make styling more consistent and nicer. 

| **Before** | **After**
| --- | ---
| cmf-tree-style-before | cmf-tree-style-after

### CODE REVIEW

File: DependencyInjection/Compiler/AddTreeBrowserAssetsPass.php [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+     * {@inheritdoc}
+     */
+    public function process(ContainerBuilder $container)
+    {
+        if (!$container->hasDefinition('sonata.admin.pool')) {
+            return;
+        }
+
+        $definition = $container->findDefinition('sonata.admin.pool');
+        $this->addAssetsToAdminPool($definition);
```
Comment (greg0ire) [inline DependencyInjection/Compiler/AddTreeBrowserAssetsPass.php]: Please remove the one-time variable : `$this->addAssetsToAdminPool($container->findDefinition('sonata.admin.pool'));`

File: Resources/views/Form/tree_browser_fields.html.twig [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+    </div>
+{% endblock %}
+
+{% block cmf_tree_select_widget_input %}
+    <div class="input-group">
+        {{ block('form_widget_simple') }}
+
+        {% if "compact" == widget %}
+            <div class="input-group-btn">
+                <button class="btn btn-primary" id="{{ id }}-cmf-tree-tooltip-toggle">{{ 'form.button.pick'|trans({}, 'CmfTreeBrowserBundle') }}</button>
```
Comment (greg0ire) [inline Resources/views/Form/tree_browser_fields.html.twig]: Please linebreak this.

File: DependencyInjection/Compiler/AddTreeBrowserAssetsPass.php [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+use Symfony\Component\DependencyInjection\ContainerBuilder;
+use Symfony\Component\DependencyInjection\Definition;
+use Symfony\Component\DependencyInjection\Reference;
+
+/**
+ * Adds javascripts and stylesheets required for the TreeSelectType.
+ *
+ * @author Wouter de Jong <wouter@wouterj.nl>
+ */
+class AddTreeBrowserAssetsPass implements CompilerPassInterface
```
Comment (greg0ire) [inline DependencyInjection/Compiler/AddTreeBrowserAssetsPass.php]: Could be final

**Comment by wouterj** [comment]
Thanks for the quick review each time @greg0ire! Should be fixed now.

**Comment by greg0ire** [comment]
Thanks @wouterj !
